#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update

rune:
  materials:
    apihost: http://services.runescape.com/m=itemdb_rs/api/catalogue/detail.json?item=
